---

- name: "Configure additional offline repos"
  yum_repository:    
    name: "{{ item.value.name }}"
    description: "{{ item.value.name }} repo"
    baseurl: "{{ item.value.baseurl }}"
    enabled: true 
    gpgcheck: "{{ item.value.gpgcheck}}"
    gpgkey: "{{ item.value.gpgkey}}"
    file: "offline"
  loop: "{{ lookup('dict', additional_offline_repos) }}"
  register: yum_results

- name: "Configure RHEL offline repos"
  yum_repository:    
    name: "{{ item.value.name }}"
    description: "{{ item.value.name }} repo"
    baseurl: "{{ item.value.baseurl }}"
    enabled: true 
    gpgcheck: "{{ item.value.gpgcheck}}"
    gpgkey: "{{ item.value.gpgkey}}"
    file: "offline"
  loop: "{{ lookup('dict', rhel_offline_repos) }}"
  when: "ansible_distribution == 'RedHat'"
  register: yum_results
  
- name: "Configure CentOS offline repos"
  yum_repository:
    name: "{{ item.value.name }}"
    description: "{{ item.value.name }} repo"
    baseurl: "{{ item.value.baseurl }}"
    enabled: true 
    gpgcheck: "{{ item.value.gpgcheck}}"
    gpgkey: "{{ item.value.gpgkey}}"
    file: "offline"
  loop: "{{ lookup('dict', centos_offline_repos) }}"
  when: "ansible_distribution == 'CentOS'"
  register: yum_results

- name: Clean repo cache
  shell: yum clean all
  when: yum_results.changed
  args:
    warn: false

- name: create pip dir
  file:
    path: "~/.pip"
    state: directory

- name: Add pip config
  template:
    src: templates/pip.conf.j2
    dest: "~/.pip/pip.conf"